use_frameworks!
platform :ios, '9.0'

target 'SegueCoordinator_Example' do
  pod 'SegueCoordinator', :path => '../'
  
end

target 'SegueCoordinatorTests' do
    pod 'SegueCoordinator', :path => '../'

end
